
FROM docker.elastic.co/kibana/kibana:7.8.0

RUN bin/kibana-plugin install https://d3g5vo6xdbdb9a.cloudfront.net/downloads/kibana-plugins/opendistro-security/opendistro_security_kibana_plugin-1.9.0.0.zip

CMD bin/kibana
